README作成
ni3520/original pull request #1
Opened 2024-10-27 12:08 UTC by ni3520

**概要**
README作成

2024-10-28 01:40 UTC, ippei-shimizu commented
対応ありがとうございます。以下の点に関してコメントします。
回答及びREADME.mdへの反映をお願いします。
...

本アプリでは「継続が苦手はユーザーに対して、毎日やったことをカレンダー形式で記録していくことで、継続へのモチベーションを向上させる」ことがメインの価値になると思いましたが、この機能のみではユーザーの継続力を持続させるには少し弱いと感じました。
理由としては、そもそも継続が苦手な方は記録をつけるだけでは続かないと思ったからになります。
そのため、毎日記録をつけたくなるような何かしらの仕掛けが必要だと感じましたがいかがでしょうか？

2024-11-01 11:36 UTC, ni3520 commented
変更コミットID 852d51570faac0ea35d56eed7ccb3ff09eb0603c
利用イメージを変更しました

色を変えて目に見える変化がわかればモチベーションにつながるかと思いました。READMEにも記載した通り、githubの草のように緑色で埋めていくようにすることで、ちょっとしたコレクション感覚でもサービスを利用できると思います。

2024-11-02 05:34 UTC, tarakish requested changes
修正確認しました。以下コメントです！

> ■サービス概要
どんなサービスなのかを３行で説明してください。

といったそれぞれの項目の説明文は不要なので削除するようにお願いします！

> 1日4時間勉強すると決めたとして、達成できた日のマスは緑色に変える。githubの草のイメージ。

良いと思います。
継続には実際に努力した量に加えて、努力している（進んでいる）感覚も大事かと思いますので（[参考](https://note.com/flower_8_7/n/nfa7dfc54c576)）、目標を立てる際に最低限のライン、理想のラインなど、レベルを分けて設定したり、その手間を省くために設定した項目からAIのAPIなどを介して、レベル分けするなどがあってよいのかなと思いました（参考程度です）
それができれば、たとえばGitHubの草はコミットの量などで色がグラデーションになるので、努力のレベルに合わせて色を濃くするなどもできるかと思います。

2024-11-03 05:47 UTC, ni3520 commented
コメントありがとうございます。
レベル分けするのがいいと思ったので取り入れさせていただきました

変更コミットIDd51d6dfa593c103e4a7d9681abb24767e891d299

2024-11-05 04:25 UTC, kenchasonakai commented
LGTMです！

現状だと技術的にアピールできるポイントが少ない印象があるので実装を進めていく中でどんな機能ならユーザーの継続を応援できるかを考えて本リリースまでに何か機能追加を出来るとよいかと思います

2024-11-05 09:41 UTC, merged